### ISSUE TITLE
.dae converter TypeError: 'dict_keys' object is not subscriptable (Python 3.10.3)

### ISSUE THREAD

**Issue by ClassicsWoTWorkshop** [SkaceKamen/wot-model-converter#12]
Attempting to use the .dae converter (obj converter works without issue, but dae converter is needed to retain animated object skinning) produces the following error message (and does not output a .dae file):

> processing Gun_01.primitives_processed
> position vector count: 6290
> position vector count: 1340
> position vector count: 3266
> position vector count: 3276
> Traceback (most recent call last):
>   File "C:\wot-model-converter\convert-primitive.py", line 181, in <module>
>     model_writer.write(tmp, filename_obj, filename_mtl)
>   File "C:\wot-model-converter\wot\ColladaModelWriter.py", line 236, in write
>     sceneRootName = primitive.nodes.keys()[0]
> TypeError: 'dict_keys' object is not subscriptable

Running latest Python version at the time of writing (3.10.3).

**Comment by atacms** [comment]
are you referring to skaceKamen's branch or my branch?

**Comment by ClassicsWoTWorkshop** [comment]
Your branch. Sorry, it looks like I posted this issue to the wrong repo...
